### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by ghost** [arendjr/text-clipper#1]
Can you make this as a bower package?

**Comment by arendjr** [comment]
No, sorry. As far as I'm concerned it's time to move on from bower.

**Comment by ghost** [comment]
I'm aware about the disadvantages of bower vs npm only solutions. The point is all my frontend libraries are manageable with bower while its possible but still unusual to manage libraries not even contain javascript (sass, images,..) with npm.

It's fine you dont like it, but what wrong about give the users a choice? All you have to do is add a bower.json, thats it. However, I've switched already to Clamp.js and quite happy with it. Thanks
