### ISSUE TITLE
Release ESM-compatible version

### ISSUE THREAD

**Issue by thewilkybarkid** [arendjr/text-clipper#25]
#22 was merged, but there hasn't been a release since. Would it be possible to make one @arendjr?

I'm trying to migrate a project from CJS to ESM using 2.2.0 (https://github.com/PREreview/prereview.org/issues/1750), and tsc is giving me the error:

`typeof import("[...]/node_modules/text-clipper/dist/index")' has no call signatures`

I've had a go and see if there's a way round it locally, but I'm guessing using the updated build will be simpler/quicker!

**Comment by arendjr** [comment]
I have released native ESM versions to Jsr.io. Installation instructions are in the README. Let me know if anything is unclear!

**Comment by thewilkybarkid** [comment]
Thanks; I got it to install using npm and it works. It looks like there are some Jest-related changes that I need to make (currently complaining about unexpected tokens, \*sigh\*).
