### ISSUE TITLE
<del> tag not supported

### ISSUE THREAD

**Issue by maggask** [arendjr/text-clipper#8]
Missing support for `<del></del>` tag, had to uninstall because of it. Maybe you would want to add that.

**Comment by arendjr** [comment]
What support would you expect for the `<del>` tag?

I added test cases for the `<ins>` and `<del>` tags, but it seems they don't need any special-support: 60c60e6399387bf8c23aaf3a4194d9789f3ad7ce

**Comment by arendjr** [comment]
Closed due to inactivity.
